## 目录
* [try_catch_finally](#try_catch_finally)
* [自动捕获异常](#自动捕获异常)
* [异常配置](#异常配置)
* [PHP5与7的异常区别](#PHP5与7的异常区别)
* [nginx-fpm模式下的error_page问题](#nginx-fpm模式下的error_page问题)
# try_catch_finally
说到异常处理自然就会想到try...catch
```
<?php
try{
  throw new Exception("test");
} catch (Exception $e) {
  var_dump($e->getMessage());
} finally {
  var_dump("finally");
}
```
一般框架都会自己封装Exception类，如HttpException或者NotFoundException等等，用这样来实现捕获不同类的异常，做不用的处理；如捕获了NotFoundException异常来加载404的专属页面，捕获HttpException异常去响应http code 200
```
<?php
class HttpException extends Exception{}
try {
	$e = new HttpException("test");
	throw $e;
} catch (HttpException $e) {
	var_dump($e->getMessage());
} catch (Exception $e) {
	var_dump($e->getMessage());
}
```
```
<?php
class HttpException extends Exception{}
try {
	$e = new HttpException("test");
	throw $e;
} catch (Exception $e) {
	if($e instanceof HttpException){
		var_dump(1);
	} else {
		var_dump(2);
	}
}
```
对于finally有一个需要注意一点，finally里面不能有return，会影响最后的返回结果
```
<?php
function test(){
	try {
		return 2;	
	} catch (Exception $e) {
	
	} finally {
		return 123;
	}
}
var_dump(test());  //123
```
# 自动捕获异常
try_catch是能捕获到异常的，但是需要手动throw，PHP可以实现自动捕获异常并且接受异常做响应的处理
